"""Added onboarding pathways & steps

Revision ID: 3edf19659bcb
Revises: e47235142938
Create Date: 2024-12-09 15:44:10.888073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3edf19659bcb'
down_revision = 'e47235142938'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('onboarding_path',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('path_name')
    )
    op.create_table('onboarding_step',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('step_name', sa.String(length=150), nullable=False),
    sa.Column('step_description', sa.Text(), nullable=True),
    sa.Column('onboarding_path_id', sa.Integer(), nullable=False),
    sa.Column('training_module_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['onboarding_path_id'], ['onboarding_path.id'], ),
    sa.ForeignKeyConstraint(['training_module_id'], ['training_module.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('onboarding_path_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_user_onboarding_path',  
            'onboarding_path',
            ['onboarding_path_id'],
            ['id']
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('onboarding_path_id')

    op.drop_table('onboarding_step')
    op.drop_table('onboarding_path')
    # ### end Alembic commands ###
