"""Add google_email to User model

Revision ID: 4496f4b00ab2
Revises: 56c79e7abc5e
Create Date: 2025-01-18 23:20:46.693697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4496f4b00ab2'
down_revision = '56c79e7abc5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_email', sa.String(length=120), nullable=True))
        batch_op.create_unique_constraint('uq_google_email',['google_email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('uq_google_email', type_='unique')
        batch_op.drop_column('google_email')

    # ### end Alembic commands ###
