"""Make video_url nullable on training_module

Revision ID: 88d985a250c1
Revises: c7e05c51a3aa
Create Date: 2025-07-21 15:31:46.129534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88d985a250c1'
down_revision = 'c7e05c51a3aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_module', schema=None) as batch_op:
        batch_op.alter_column('video_url',
               existing_type=sa.VARCHAR(length=300),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_module', schema=None) as batch_op:
        batch_op.alter_column('video_url',
               existing_type=sa.VARCHAR(length=300),
               nullable=False)

    # ### end Alembic commands ###
