"""Add active flag (nullable) to TrainingModule

Revision ID: df399eacfe45
Revises: 88d985a250c1
Create Date: 2025-07-21 22:41:00.782316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df399eacfe45'
down_revision = '88d985a250c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_module', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_module', schema=None) as batch_op:
        batch_op.drop_column('active')

    # ### end Alembic commands ###
